# -*- coding: utf-8 -*-
"""HW 6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbtSPqgLj0CtCdv79-xhffqg0XlDNtY_
"""

#Exercise 1
def WhoAmI():
  return 'ldh2134'

print(WhoAmI())

#Exercise 2

import yfinance as yf
import pandas as pd
import numpy as np

def get_stock_data(symbol, start, end):
  data = yf.download(symbol, start=start, end=end)
  prices = data['Close']
  return prices

#Example usage for January - September 2025:
prices = get_stock_data('AAPL', '2025-01-01', '2025-09-30')
print(type(prices))
pricevec = prices.values

#Compute the returns
n = len(pricevec)
ratiovec = pricevec[1:n] / pricevec[:n-1]

def get_returns(pricevec):
  n = len(pricevec)
  ratiovec = pricevec[1:n] / pricevec[:n-1]
  returns = ratiovec - 1
  return returns

#Example of using get_returns
returns = get_returns(pricevec)
print(returns)

#Print the following:
print("Average return:", np.mean(returns))
print("Max return:", np.max(returns))
print("Min return:", np.min(returns))
print("Standard deviation of return:", np.std(returns))

#Exercise 3

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def percent_var(r, alpha):
  #This function returns the left tail value and displays a histogram
  #alpha = risk level
  # r = a vector of stock returns
  #out = positively stated value of r at the 1-alpha percentile

  plt.hist(r, bins=50, alpha=0.75)
  plt.show()
  out = np.percentile(r, (1-alpha)*100) #Calculate the percentile
  return abs(out) #Return the absolute value of the calculated percentile

#Example usage with Apple returns:
alpha = 0.01 #1% VaR (99% confidence)
my_percent_var = percent_var(returns, alpha)
print("Percent VaR (alpha=0.01):", my_percent_var)

#Exercise 4

import numpy as np

def es(losses, alpha=None, VaR=None):
  """
  Calculate the Expected Shortfall (ES) of losses.

  :param losses: array of positively stated loss values
  :param alpha: risk level (e.g., 0.99 for 99%)
  :param VaR: dollar value or percentage specifying the VaR threshold
  :return: Expected Shortfall as the average of losses exceeding VaR
  """
  if VaR is None:
    #If VaR is not provided, determine VaR based on the alpha percentile
    VaR = np.percentile(losses, 100*(1-alpha))

  #Calculate ES as the average of losses exceeding the VaR threshold
  es_value = np.mean(losses[losses > VaR])
  return es_value

#Example/test usage:
#Convert returns to losses for risk calculations (abs or negative returns)
losses = np.abs(returns)

#Test the ES function with a risk level of 1%
es_alpha = es(losses, alpha=0.99)
print("ES with alpha=0.99:", es_alpha)

#Test the ES function with a specific VaR value (for example, VaR = 0.05)
VaR_value = np.percentile(losses, 100*(1-0.99))
es_var = es(losses, VaR=VaR_value)
print("ES with VaR=", VaR_value, ":", es_var)