# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pusQVayDHwt2N5qag2t6XJOnhh-ttQ3
"""

def WhoAmI():
  return "ldh2134"

print (WhoAmI())

# qOOP1
import numpy as np

class Bond:
    def __init__(self, face, ytm, coupon_rate, maturity):
        self.face = face  # par value (e.g. 1000)
        self.ytm = ytm    # yield to maturity (as decimal, 5% → 0.05)
        self.coupon_rate = coupon_rate  # annual coupon rate (as decimal)
        self.maturity = maturity  # in years

    def getPrice(self):
        # price = PV of coupons + PV of face value
        price = 0
        for t in range(1, self.maturity + 1):
            price += self.coupon_rate * self.face / (1 + self.ytm) ** t
        price += self.face / (1 + self.ytm) ** self.maturity
        return price

    def getDuration(self):
        # Macaulay Duration = weighted average of the times to coupon payments
        price = self.getPrice()
        weighted_sum = 0
        for t in range(1, self.maturity + 1):
            weighted_sum += t * (self.coupon_rate * self.face) / (1 + self.ytm) ** t
        weighted_sum += self.maturity * self.face / (1 + self.ytm) ** self.maturity
        duration = weighted_sum / price
        return duration

    def __repr__(self):
        return f"Bond(face={self.face}, ytm={self.ytm}, coupon_rate={self.coupon_rate}, maturity={self.maturity})"

    def __str__(self):
        return f"Bond: Face={self.face}, Coupon={self.coupon_rate*100}%, YTM={self.ytm*100}%, Maturity={self.maturity} years"

bond1 = Bond(1000, 0.05, 0.06, 5)
print(bond1)
print("Price:", bond1.getPrice())
print("Duration:", bond1.getDuration())

#q00P2

class ConvertibleBond(Bond):
    def __init__(self, face, ytm, coupon_rate, maturity, conversion_ratio, conversion_price):
        super().__init__(face, ytm, coupon_rate, maturity)
        self.conversion_ratio = conversion_ratio  # number of shares per bond
        self.conversion_price = conversion_price  # price at which bond can convert

    def getPrice(self, stock_price=None):
        # Convertible bond price ≈ max(straight bond price, conversion value)
        straight_price = super().getPrice()
        if stock_price is not None:
            conversion_value = self.conversion_ratio * stock_price
            return max(straight_price, conversion_value)
        else:
            return straight_price

    def getDuration(self):
        # Duration is usually less due to conversion, but we'll use the parent version
        return super().getDuration()

    def __repr__(self):
        return (f"ConvertibleBond(face={self.face}, ytm={self.ytm}, coupon_rate={self.coupon_rate}, "
                f"maturity={self.maturity}, conversion_ratio={self.conversion_ratio}, "
                f"conversion_price={self.conversion_price})")

    def __str__(self):
        return (f"Convertible Bond: Face={self.face}, Coupon={self.coupon_rate*100}%, "
                f"YTM={self.ytm*100}%, Maturity={self.maturity} years, "
                f"Conversion Ratio={self.conversion_ratio}, Conversion Price={self.conversion_price}")

conv_bond = ConvertibleBond(1000, 0.04, 0.05, 5, conversion_ratio=20, conversion_price=50)
print(conv_bond)
print("Price (no stock):", conv_bond.getPrice())
print("Price (stock $55):", conv_bond.getPrice(stock_price=55))
print("Duration:", conv_bond.getDuration())